### ISSUE TITLE
v1.listDockerImages provides error response RESOURCE_PROJECT_INVALID

### ISSUE THREAD

**Issue by Peter-Sparksuite** [googleapis/nodejs-artifact-registry#144]
- What you're trying to do

The equivalent of the following gcloud CLI command (which works):

```
gcloud artifacts docker images list us-east1-dkrimgs.pkg.dev/dev-infrastructure/images-v1 --format=json --include-tags
```

using the v1.listDockerImages() method.  I'd also like to have it include the 'tags' (not sure how exactly to get that flag passed down, if needed, as docs and examples that I've seen are not too helpful here).

- What code you've already tried

```ts
import { v1 } from '@google-cloud/artifact-registry';

(async () => {

const client = new v1.ArtifactRegistryClient();
const stub = await client.initialize();

console.log('stub:');
console.dir(stub); // What looks like good results are visible as result of this

const projectId = await client.getProjectId();
console.log('projectId:', projectId); // good result is seen here (got it from the environment settings / client .json file, I guess)

const resp = await client.listDockerImages({
parent: 'us-east1-dkrimgs.pkg.dev/dev-infrastructure/images-v1'
});

// does not get here
})();

```

- Any error messages you're getting

```
error: Error: 3 INVALID_ARGUMENT: Invalid resource field value in the request.
    at Object.callErrorFromStatus (/app/.yarn/cache/@grpc-grpc-js-npm-1.6.7-2e10ef0dbb-2668b08c2e.zip/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/.yarn/cache/@grpc-grpc-js-npm-1.6.7-2e10ef0dbb-2668b08c2e.zip/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/app/.yarn/cache/@grpc-grpc-js-npm-1.6.7-2e10ef0dbb-2668b08c2e.zip/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/.yarn/cache/@grpc-grpc-js-npm-1.6.7-2e10ef0dbb-2668b08c2e.zip/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/.yarn/cache/@grpc-grpc-js-npm-1.6.7-2e10ef0dbb-2668b08c2e.zip/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 3,
  details: 'Invalid resource field value in the request.',
  metadata: Metadata {
    internalRepr: Map(3) {
      'grpc-server-stats-bin' => [Array],
      'google.rpc.errorinfo-bin' => [Array],
      'grpc-status-details-bin' => [Array]
    },
    options: {}
  },
  statusDetails: [
    ErrorInfo {
      metadata: [Object],
      reason: 'RESOURCE_PROJECT_INVALID',
      domain: 'googleapis.com'
    }
  ],
  reason: 'RESOURCE_PROJECT_INVALID',
  domain: 'googleapis.com',
  errorInfoMetadata: {
    method: 'google.devtools.artifactregistry.v1.ArtifactRegistry.ListDockerImages',
    service: 'artifactregistry.googleapis.com'
  }
}
```

All seems good until the `.listDockerImages()` is invoked.

From what I can see, I'm providing the 'parent' value in the request object, with exactly the same value there as what the `gcloud` CLI accepts without issue.

Node version is: 16.14.2
@google-cloud/artifact-registry module version: 1.3.0 (latest)

Assistance is appreciated!

**Comment by ace-n** [comment]
@Peter-Sparksuite thanks for the issue.

I'm not too sure about the tags specifically, but I'm curious as to whether this might work:

For the `parent` argument, can you change the value to the following?
> projects/dev-infrastructure/locations/us-east1/repositories/images-v1

**Context:**
`gcloud` uses the format documented [here](https://cloud.google.com/sdk/gcloud/reference/artifacts/docker/images/list#IMAGE_PATH), whereas I suspect the client libraries use [the format used by the REST API](https://cloud.google.com/artifact-registry/docs/reference/rest#rest-resource:-v1.projects.locations.repositories.dockerimages)
